version: '3.8'
services:
  tabbyapi:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DO_PULL=true
    ports:
      - "5000:5000"
    environment:
      - NAME=TabbyAPI
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
